name: riak_client
version: 0.6.0
authors:
- Istvan Soos <istvan.soos@gmail.com>
- Ian M. Jones <ian@ianmjones.com>
description: Riak Client using the HTTP API
homepage: https://code.google.com/p/riak-dart/
documentation: https://code.google.com/p/riak-dart/
dependencies:
  intl: 0.5.20
dev_dependencies:
  args: any
  unittest: any
