name: riak_client
authors:
- Istvan Soos <istvan.soos@gmail.com>
- Ian M. Jones <ian@ianmjones.com>
version: 0.6.1
homepage: https://code.google.com/p/riak-dart/
description: Riak Client using the HTTP API
documentation: https://code.google.com/p/riak-dart/
dependencies:
  fixnum: any
  http_server: any
  intl: 0.5.20
  protobuf: any
dev_dependencies:
  args: any
  unittest: any
